In [1]:
import pandas as pd
df=pd.read_excel(r"D:\github\pandas\output.xlsx",index_col="ID")
df.to_excel(r"D:\github\pandas\output.xlsx")
print("Done")

Done


In [3]:
import pandas as pd
d={'x':100,'y':200,'z':300}
print(d["x"])

100


In [4]:
list=[]
for i in range(1,100):
    if i%2!=0:
        list.append(i)
print(list)

list2=[]
for i in range(1,100,2):
    list2.append(i)
print(list2)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]


In [5]:
a=37
flag=False
for i in range(2,a):
    if a%i==0:
        flag=True
        break
if flag:
    print('是合数')
else:
    print('是素数')
        

是素数


In [ ]:
#方法一：非递归
n=4
sum=1
for i in range(1,n+1):
    sum*=i
print(sum)
#方法二：递归
def jie_cheng(num):
    if num==1:
        return 1
    else:
        return num*jie_cheng(num-1)
print(jie_cheng(n))

24
24


In [8]:
import numpy as np
print(np.__version__)
np.show_config()

2.2.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-3gj71u4o/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-3gj71u4o/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.28  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy/numpy/.openblas
    version: 0.3.28
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-3gj71u4o/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-3gj71u4o/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.

In [12]:
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [18]:
data=np.zeros((10,10))
print("%d bytes"%(data.size*data.itemsize))

800 bytes


In [19]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [20]:
np.info(np.zeros)

zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Also
--------

In [23]:
b= np.zeros(10)
b[4]=1
print(b)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [25]:
data=np.arange(10,50)
print(data)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [33]:
data1=np.arange(50)
data1=data[::-1]
print(data1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [48]:
data=np.arange(9).reshape(3,3)
print(data)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [49]:
nz=np.nonzero([1,2,0,0,4,0])
nz

(array([0, 1, 4]),)

In [50]:
data=np.eye(3)
data

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

12.创建一个3x3x3的随机数组

In [4]:
import numpy as np
data= np.random.random((3,3,3))
data

array([[[0.72186816, 0.5773447 , 0.38859499],
        [0.34095747, 0.89968805, 0.77193987],
        [0.26222514, 0.18469464, 0.74133819]],

       [[0.65060361, 0.56099196, 0.04717751],
        [0.35834991, 0.79928219, 0.88072535],
        [0.73349217, 0.47328835, 0.21371993]],

       [[0.46608985, 0.07649429, 0.63492116],
        [0.60153578, 0.73130535, 0.96608936],
        [0.46157639, 0.96888892, 0.9398318 ]]])

In [10]:
data=np.random.random((10,10))
datamin,datamax=data.min(),data.max()
print(datamin,datamax)

0.030752406824746337 0.9811053897688359


In [13]:
data=np.random.random(30)
m=data.mean()
print(m)

0.5199930966212628


In [16]:
data=np.arange(30)
print(data.mean())

14.5


In [20]:
data=np.ones((10,10))
data[1:-1,1:-1]=0
print(data)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


16对于一个存在在数组，如何添加一个用0填充的边界

In [27]:
data=np.ones((5,5))
data=np.pad(data,pad_width=1,mode='constant',constant_values=0)
print(data)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


17,以下表达式运行的结果分别是什么？

In [33]:
0*np.nan
np.nan==np.nan
np.inf>np.nan
np.nan-np.nan
0.3==3*0.1

False

In [34]:
print(0*np.nan)

nan


In [35]:
print(np.nan==np.nan)

False


In [36]:
print(np.inf>np.nan)

False


In [37]:
print(np.nan-np.nan)

nan


In [38]:
print(0.3==3*0.1)

False


18,创建一个5X5的矩阵，并设置值1,2,3,4落在其对角线下方位置 将K的值改为1,0看看

In [51]:
data=np.diag(1+np.arange(4),k=1)
print(data)

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


19，创建一个8X8的矩阵，并且设置成棋盘样式

In [55]:
data=np.zeros((8,8),dtype=(int))
# 方法 1：利用 (i + j) % 2 判断奇偶
data[1::2,::2]=1  # 奇数行，偶数列置1
data[::2,1::2]=1  # 偶数行，奇数列置1
print(data)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [57]:
import numpy as np
# 方法 2：用 2x2 的基本块拼接
base = np.array([[0, 1], [1, 0]])
chess_board = np.tile(base, (4, 4))  # 重复 4x4 次

print(chess_board)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


20，考虑一个（6,7,8）形状的数组，其第100个元素的索引（x,y,z)是什么？

In [59]:
np.unravel_index(100,(6,7,8))  #扁平索引（从 0 开始）。

(np.int64(1), np.int64(5), np.int64(4))

21 用tile函数去创建一个8x8的棋盘样式矩阵

In [65]:
data=np.tile(np.array([[0,1],[1,0]]),(4,4))
print(data)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


22 对一个5x5的随机矩阵做归一化

In [70]:
data=np.random.random((5,5))
datamax,datamin=data.max(),data.min()
data=(data-datamin)/(data-datamax)
print(data)

[[-19.91152714  -3.72723527          inf -16.63132626  -0.25149318]
 [ -1.43604786  -2.96684791 -21.06756149  -3.65028367  -1.18061952]
 [ -0.03127932  -0.14262566  -0.18045865  -1.00154716  -0.3205705 ]
 [ -4.39351454  -0.          -0.08816324  -0.05394018  -0.20803775]
 [ -0.52437492  -0.16939402  -0.95484743  -2.08740518  -0.38129158]]


C:\Users\garfi\AppData\Local\Temp\ipykernel_34528\649853065.py:3: RuntimeWarning: divide by zero encountered in divide
  data=(data-datamin)/(data-datamax)


In [ ]:
23 创建一个将颜色描述为（RGBA）四个无符号字节的自定义dtype?

In [72]:
color=np.dtype([('r',np.ubyte,1),
                ('g',np.ubyte,1),
                ('b',np.ubyte,1),
                ('a',np.ubyte,1)])
color

dtype([('r', 'u1', (1,)), ('g', 'u1', (1,)), ('b', 'u1', (1,)), ('a', 'u1', (1,))])

24 一个5X3的矩阵与一个3X2的矩阵相乘，实矩阵乘积是什么？

In [76]:
data=np.dot(np.ones((5,3)),np.ones((3,2)))
data

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

25 给定一个一维数组，对其在3到8之间的所有元素取反

In [79]:
data=np.arange(10)
data[(3<data)&(data<=8)]*=-1
print(data)

[ 0  1  2  3 -4 -5 -6 -7 -8  9]


26 下面脚本运行后的结果是什么？

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

In [81]:
print(sum(range(5),-1))

9


In [82]:
from numpy import *
print(sum(range(5),-1))

10


27 考虑一个整数向量Z,下列表达合法的是哪个?

In [84]:
Z**Z
2<<Z>>2
Z<-Z
1j*Z
Z/1/1
Z<Z>Z

NameError: name 'Z' is not defined

In [86]:
Z=np.arange(5)
Z**Z

array([  1,   1,   4,  27, 256])

In [87]:
Z=np.arange(5)
2<<Z>>2

array([0, 1, 2, 4, 8])

In [88]:
Z=np.arange(5)
Z<-Z

array([False, False, False, False, False])

In [89]:
Z=np.arange(5)
1j*Z

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])

In [90]:
Z=np.arange(5)
Z/1/1

array([0., 1., 2., 3., 4.])

In [92]:
Z=np.arange(5)
Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
28 下列表达式的结果分别是什么？

In [ ]:
np.array(0)/np.array(0)
np.array(0)//np.array(0)
np.array([np.nan]).astype(int).astype(float)

In [93]:
np.array(0)/np.array(0)

C:\Users\garfi\AppData\Local\Temp\ipykernel_34528\1571972474.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0)/np.array(0)


np.float64(nan)

In [94]:
np.array(0)//np.array(0)

C:\Users\garfi\AppData\Local\Temp\ipykernel_34528\3350367291.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0)//np.array(0)


np.int64(0)

In [95]:
np.array([np.nan]).astype(int).astype(float)

C:\Users\garfi\AppData\Local\Temp\ipykernel_34528\699728972.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

29 如何从零位对浮点数组做舍入？

In [101]:
data = np.random.randint(0,10,10)
data2 = np.random.randint(0,10,10)
print(np.intersect1d(data,data2))

[1 2 8]


In [102]:
data=np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(data)),data))

[-7.  8.  2. -7.  8.  4.  9.  4. -3.  2.]


30 如何找到两个数组中的共同元素？

In [ ]:
data = np.random.randint(0,10,10)
data2 = np.random.randint(0,10,10)
print(np.intersect1d(data,data2))

In [ ]:
31 如何忽略所有的numpy警告（）

32 下面的表达式是正确的吗？

In [104]:
np.sqrt(-1)==np.emath.sqrt(-1)

C:\Users\garfi\AppData\Local\Temp\ipykernel_34528\3898620780.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1)==np.emath.sqrt(-1)


np.False_

33. 如何得到昨天，今天，明天的日期？

In [111]:
yesterday=np.datetime64('today','D')-np.timedelta64(1,'D')
yesterday

np.datetime64('2025-04-17')

In [110]:
today=np.datetime64('today','D')
today

np.datetime64('2025-04-18')

In [114]:
tomorrow=np.datetime64('today','D')+np.timedelta64(1,'D')
tomorrow

np.datetime64('2025-04-19')

In [ ]:
34 如何得到所以的与2016年7月对应的日期？

In [117]:
data=np.arange('2016-07','2016-08',dtype='datetime64[D]')
data

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

35 如何直接在位计算（A+B)*(-A/2)(不建立副本）？