In [5]:
import numpy as np

In [11]:
print(np.__version__)
np.show_config()

1.24.3
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['openblas\\lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None

In [13]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [19]:
data=np.zeros((10,10))

In [25]:
print("%d bytes"%(data.size*data.itemsize))

800 bytes


In [27]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [32]:
datas=np.zeros(10)
datas[5]=1
print(datas)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [39]:
data = np.arange(10,50)
print(data)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [43]:
data=np.arange(50)
data1=data[::-1]
print(data1)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [48]:
9.创建一个3*3并且值从0到8的矩阵

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [49]:
data=np.arange(9).reshape(3,3)
print(data)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [56]:
# 10.找到数组[1,2,0,0,4，0]中非0元素索引
nz=np.nonzero([1,2,0,0,4,0])
nz

(array([0, 1, 4], dtype=int64),)

In [57]:
#11创建一个3X3的单位矩阵
data=np.eye(3)
data

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
data = np.random.random ((3,3,3))
data

array([[[0.63887362, 0.05855474, 0.70071537],
        [0.08174657, 0.74477072, 0.4450875 ],
        [0.56996524, 0.22646346, 0.6196591 ]],

       [[0.36224864, 0.05755565, 0.58178305],
        [0.47808174, 0.94167484, 0.50802291],
        [0.51556973, 0.65269395, 0.25280002]],

       [[0.55766933, 0.8013297 , 0.4838603 ],
        [0.68408277, 0.10898226, 0.94695418],
        [0.6120844 , 0.37982129, 0.66955448]]])

In [9]:
#创建一个10*10的随机数组并找到它的最大值和最小值
data=np.random.random((10,10))
datamin,datamax=data.min(),data.max()
print(datamin,datamax)

0.0033719966107345067 0.9981166129901741


In [11]:
#创建一个长度为30的随机向量并找到它的平均值
data=np.random.random(30)
m=data.mean()
print(m)

0.5598959373897049


In [14]:
#15.创建一个二维数组，其中边界值为1，其余值为0
data=np.ones((10,10))
data[1:-1,1:-1]=0
print(data)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [19]:
#16对于一个存在的数组，如何添加一个用0填充的边界？
data=np.ones((5,5))
data=np.pad(data,pad_width=1,mode="constant",constant_values=0)
print(data)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [21]:
#17以下表达式运行的结果分别是什么
0*np.nan
np.nan==np.nan
np.inf>np.nan
np.nan-np.nan
0.3==3*0.1

False

In [23]:
print(np.nan==np.nan)

False


In [35]:
#18.创建一个5*5的矩阵，并设置值1，2，3，4落在其对角线下方位置
data = np.diag(1+np.arange(4),k=-1)
data

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [38]:
x=np.arange(9).reshape((3,3))
data=np.diag(np.diag(x))
print(data)

[[0 0 0]
 [0 4 0]
 [0 0 8]]


In [40]:
a = np.ones(25).reshape((5,5))
b = [1,2,3,4]
print(np.diag(b,k = -1))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [48]:
#19.创建一个8*8的矩阵，并且设置成棋盘样式
data=np.zeros((8,8),dtype=int)
data[1::2,::2]=1
data[::2,1::2]=1
print(data)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [50]:
#20考虑一个（6，7，8）形状的数组，其第100个元素的索引（x,y,x)是什么
np.unravel_index(100,(6,7,8))

(1, 5, 4)

In [59]:
#21用tile函数去创建一个8x8的棋盘样式矩阵
data1 = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(data1)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [61]:
#22 对一个5x5的随机矩阵做归一化
data=np.random.random((5,5))
datamax,datamin=data.max(),data.min()
data=(data-datamin)/(datamax-datamin)
print(data)

[[1.03795667e-01 5.46223506e-01 7.85935599e-01 8.20699656e-01
  6.90643592e-01]
 [2.99678680e-01 4.23073604e-01 9.10691831e-02 9.78330486e-01
  4.22397006e-01]
 [1.75905353e-01 9.59304910e-01 8.96221396e-05 7.62478083e-01
  5.19992633e-01]
 [1.06354791e-01 5.52054076e-01 6.98045025e-02 0.00000000e+00
  2.33318794e-01]
 [3.33336209e-01 4.96888778e-01 2.87311822e-01 5.12152378e-01
  1.00000000e+00]]
