In [1]:
import pandas as pd
df=pd.read_excel(r"D:\github\pandas\output.xlsx",index_col="ID")
df.to_excel(r"D:\github\pandas\output.xlsx")
print("Done")

Done


In [2]:
import numpy as np
import pandas as pd
df=pd.DataFrame(pd.read_csv('name.csv',header=1))
df=pd.DataFrame(pd.read_excel('name.xlsx'))

FileNotFoundError: [Errno 2] No such file or directory: 'name.csv'

In [6]:
import pandas as pd
d={'x':100,'y':200,'z':300}
s1=
print(d["x"])

100


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


800 bytes


add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


[[0 1 2]
 [3 4 5]
 [6 7 8]]


[[0 1 2]
 [3 4 5]
 [6 7 8]]


(array([0, 1, 4], dtype=int64),)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[[0.19088387, 0.35259672, 0.27238784],
        [0.55919469, 0.30752507, 0.26078981],
        [0.8552263 , 0.99741821, 0.91202211]],

       [[0.03924192, 0.47042925, 0.32653825],
        [0.25838202, 0.83548537, 0.15423674],
        [0.88396049, 0.39074961, 0.20280933]],

       [[0.86688832, 0.06347097, 0.65496387],
        [0.94233374, 0.79778621, 0.6035265 ],
        [0.65247629, 0.11952257, 0.21868683]]])